### ISSUE TITLE
new interesting project like PyDPS

### ISSUE THREAD

**Issue by HBerecz** [Haschtl/PyDPS#2]
I have used your Python GUI for DPS3005 since 2018. It is really excellent.

Now I use another Bluetooth Device 'Ruideng UM25C'
https://www.manualslib.com/products/Ruideng-Um25c-10243666.html
with a not very good Android App.

Perhaps this would be a very interesting project for a Python GUI that shows the graph in the same excellent way as your PyDPS.

Could you make it possible?

**Comment by Haschtl** [comment]
Nice, that you like my tool!

I'm not actively using this tool anymore for myself.

This tool is not programmed in a scalable manner - extending the usage to different devices would require some more changes (currently the GUI and the Backend-Code are mixed, this would need to be split, so that the backend-code can be exchanged for different devices)

Feel free to fork this repository and implement it for yourself.
There is another console-tool, which supports DPS and UM25, this might be helpful: https://github.com/rfinnie/rdserialtool
